version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./data/pure_KazRoBERTa:/model:ro
    networks:
      - app-network

  ui:
    build:
      context: ./ui
    ports:
      - "7860:7860"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000/predict
    networks:
      - app-network

networks:
  app-network:
    driver: bridge