import os
import unicodedata
import torch
import gradio as gr
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers_interpret import SequenceClassificationExplainer
from huggingface_hub import snapshot_download

MODEL_REPO = "nKa1i/kazroberta-kk-ai-detection"
LABEL_MAP = {0: "human", 1: "ai"}

print("Downloading model from HF Hub...")
model_path = snapshot_download(repo_id=MODEL_REPO)
print(f"Model downloaded to {model_path}")

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSequenceClassification.from_pretrained(model_path)
model.config.id2label = {0: "human", 1: "ai"}
model.config.label2id = {"human": 0, "ai": 1}
model.eval()
explainer = SequenceClassificationExplainer(model, tokenizer)
print("Model loaded.")


def predict_and_explain(text):
    if not text or len(text.strip()) < 10:
        return "Please enter at least 10 characters.", ""

    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)
    with torch.no_grad():
        outputs = model(**inputs)
    probs = torch.softmax(outputs.logits, dim=1)[0]
    pred_id = torch.argmax(probs).item()
    confidence = probs[pred_id].item()
    label = LABEL_MAP.get(pred_id, "unknown").upper()
    summary = f"Prediction: {label}\nConfidence: {confidence:.2%}"

    # Attribution
    word_attributions = explainer(text)
    scores = [abs(s) for _, s in word_attributions]
    max_score = max(scores) if max(scores) > 0 else 1.0
    threshold = 0.4 * max_score

    spans = []
    evidence = []

    for word, score in word_attributions:
        decoded = tokenizer.convert_tokens_to_string([word]).strip()
        if not decoded:
            continue
        if all(ord(c) in (0xFFFD, 0xFE0F, 0x200D, 0x200B, 0x200C) or
               unicodedata.category(c) in ('Cc', 'Cf') for c in decoded):
            continue

        intensity = min(abs(score) / max_score, 1.0)
        adjusted = score if explainer.predicted_class_index == 0 else -score

        if abs(score) < threshold:
            spans.append(f'<span style="padding:1px 3px;margin:1px;display:inline-block;font-size:14px;">{decoded}</span>')
        else:
            if adjusted > 0:
                r, g, b = int(60 - 60*intensity), int(180*intensity+60), int(60 - 60*intensity)
            else:
                r, g, b = int(180*intensity+60), int(60 - 60*intensity), int(60 - 60*intensity)
            alpha = 0.2 + 0.7 * intensity
            style = f"background-color:rgba({r},{g},{b},{alpha:.2f});border-radius:3px;padding:1px 3px;margin:1px;display:inline-block;font-size:14px;"
            spans.append(f'<span style="{style}">{decoded}</span>')
            evidence.append((decoded, adjusted, abs(score) / max_score))

    evidence.sort(key=lambda x: x[2], reverse=True)

    evidence_rows = ""
    for word, adjusted, weight in evidence:
        direction = "HUMAN" if adjusted > 0 else "AI"
        bar_color = "rgba(60,200,60,0.7)" if adjusted > 0 else "rgba(200,60,60,0.7)"
        bar_width = int(weight * 120)
        evidence_rows += (
            f'<tr>'
            f'<td style="padding:3px 8px;font-size:13px;">{word}</td>'
            f'<td style="padding:3px 8px;font-size:13px;color:{"#6f6" if adjusted > 0 else "#f66"};">{direction}</td>'
            f'<td style="padding:3px 8px;"><div style="width:{bar_width}px;height:10px;background:{bar_color};border-radius:3px;"></div></td>'
            f'</tr>'
        )

    evidence_table = (
        '<table style="margin-top:10px;border-collapse:collapse;width:100%;">'
        '<tr>'
        '<th style="text-align:left;padding:3px 8px;font-size:12px;opacity:0.6;">Token</th>'
        '<th style="text-align:left;padding:3px 8px;font-size:12px;opacity:0.6;">Signal</th>'
        '<th style="text-align:left;padding:3px 8px;font-size:12px;opacity:0.6;">Weight</th>'
        '</tr>'
        + evidence_rows + '</table>'
    )

    html = (
        '<div style="line-height:2.2;padding:8px;">'
        + " ".join(spans)
        + '<hr style="opacity:0.2;margin:12px 0;">'
        + '<small style="opacity:0.6;">Key evidence (sorted by influence)</small>'
        + evidence_table
        + '</div>'
    )
    return summary, html


demo = gr.Interface(
    fn=predict_and_explain,
    inputs=gr.Textbox(lines=5, placeholder="Enter Kazakh product/app review text here...", label="Text Input"),
    outputs=[
        gr.Textbox(label="Result"),
        gr.HTML(label="Token Importance (🟢 pushed toward HUMAN · 🔴 pushed toward AI)")
    ],
    title="KazRoBERTa AI-Text Detector",
    description="Detects whether a Kazakh product review is written by a human or generated by AI. Highlights which words influenced the decision.",
    flagging_mode="never"
)

if __name__ == "__main__":
    demo.launch()
