import os
import gradio as gr
import requests

API_URL = os.environ.get("API_URL", "http://api:8000")

def predict_text(text):
    if not text or len(text.strip()) < 10:
        return "Please enter at least 10 characters.", ""

    try:
        response = requests.post(
            f"{API_URL}/explain",
            json={"text": text.strip()},
            timeout=30
        )
        response.raise_for_status()
        data = response.json()

        label = data.get("label", "unknown").upper()
        confidence = data.get("confidence", 0.0)
        html = data.get("html", "")

        summary = f"Prediction: {label}\nConfidence: {confidence:.2%}"
        return summary, html

    except requests.exceptions.ConnectionError:
        return "Error: Service unavailable (API unreachable).", ""
    except requests.exceptions.Timeout:
        return "Error: Request timed out.", ""
    except Exception as e:
        return f"Error: {str(e)}", ""

demo = gr.Interface(
    fn=predict_text,
    inputs=gr.Textbox(
        lines=5,
        placeholder="Enter Kazakh product/app review text here...",
        label="Text Input"
    ),
    outputs=[
        gr.Textbox(label="Result"),
        gr.HTML(label="Token Importance (green = human signal, red = AI signal)")
    ],
    title="KazRoBERTa AI-Text Detector",
    description="Detects whether a Kazakh product review is written by a human or generated by AI. Highlights which words influenced the decision.",
    flagging_mode="never"
)

if __name__ == "__main__":
    demo.launch(server_port=7860)
