import os
import gradio as gr
import requests

API_URL = os.environ.get("API_URL", "http://api:8000/predict")

def predict_text(text):
    if not text or len(text.strip()) < 10:
        gr.Warning("Input is too short! Please enter at least 10 characters.")
        return "N/A"

    try:
        response = requests.post(API_URL, json={"text": text.strip()})
        response.raise_for_status()
        data = response.json()
        label = data.get("label", "Unknown")
        confidence = data.get("confidence", 0.0)

        # Format the output nicely
        return f"Prediction: {label.upper()}\nConfidence: {confidence:.2%}"

    except requests.exceptions.ConnectionError:
        return "Error: Service unavailable (API unreachable)."
    except Exception as e:
        return f"Error: {str(e)}"

# Define the Gradio interface
demo = gr.Interface(
    fn=predict_text,
    inputs=gr.Textbox(lines=5, placeholder="Enter text in Kazakh here...", label="Text Input"),
    outputs=gr.Textbox(label="Detection Result"),
    title="KazRoBERTa AI-Text Detector",
    description="Detects whether a given Kazakh text is written by a human or generated by AI.",
    allow_flagging="never"
)

if __name__ == "__main__":
    # The Gradio server will bind to 0.0.0.0 because of the GRADIO_SERVER_NAME env var set in Dockerfile
    demo.launch(server_port=7860)